# Generated by Django 4.0.10 on 2025-02-01 07:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="firstname",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="lastname",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="phonenumber",
            new_name="phone_number",
        ),
    ]
