# Generated by Django 4.0.10 on 2025-02-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_firstname_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("USER", "User"),
                    ("DOCTOR", "Doctor"),
                    ("NURSE", "Nurse"),
                    ("PHARMACIST", "Pharmacist"),
                    ("PHYSICIAN", "Physician"),
                    ("NURSE_MIDWIFE", "Nurse Midwife"),
                    ("HEALTH_EDUCATOR", "Health Educator"),
                    ("HEALTH_ADVISOR", "Health Advisor"),
                    ("HEALTH_CENTER", "Health Center"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
    ]
