# Generated by Django 4.0.10 on 2025-02-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_customuser_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("USER", "User"),
                    ("USER_GIRL", "User Girl"),
                    ("USER_BOY", "User Boy"),
                    ("USER_GIRL_BOY", "User Girl Boy"),
                    ("USER_WOMEN", "User Women"),
                    ("USER_PREGNANT", "User Pregnant"),
                    ("DOCTOR", "Doctor"),
                    ("NURSE", "Nurse"),
                    ("PHARMACIST", "Pharmacist"),
                    ("PHYSICIAN", "Physician"),
                    ("NURSE_MIDWIFE", "Nurse Midwife"),
                    ("HEALTH_EDUCATOR", "Health Educator"),
                    ("HEALTH_ADVISOR", "Health Advisor"),
                    ("HEALTH_CENTER", "Health Center"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
    ]
