# Generated by Django 5.0 on 2024-02-04 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LastMenstrualPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("current_date", models.DateField(default=datetime.datetime.now)),
                ("days_pregnant", models.IntegerField(blank=True, null=True)),
                ("weeks_pregnant", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
