# Generated by Django 5.0 on 2024-02-10 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("umubyeyi", "0005_lastmenstrualperiod_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lastmenstrualperiod",
            name="trimester",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
